#!/usr/bin/expect -f
set timeout 20
spawn ssh -o StrictHostKeyChecking=no root@62.72.7.2
expect {
  "password:" { send ".3+ml3&LKxGw6N1DbZd5\r" }
}
expect "#"
send "cd /root/chatgruposyst/codatendechat-main\r"
expect "#"
# Verify login as user 'user' with env PGPASSWORD
send "docker compose exec -e PGPASSWORD=senha postgres psql -U user -d db_name -c '\\conninfo'\r"
expect "#"
send "exit\r"
expect eof
